### ISSUE TITLE
Add support for magnets?

### ISSUE THREAD

**Issue by scriptzteam** [brycied00d/PHP-Transmission-Class#25]
Add support for magnets?

**Comment by brycied00d** [comment]
https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt suggests there's no RPC support in `torrent-add` for adding a magnet: URIs.

**Comment by scriptzteam** [comment]
yes       | torrent-get          | new arg "magnetLink"

**Comment by brycied00d** [comment]
`torrent-get` is for pulling information back out of Transmission, and in the case of `magnetLink` it returns the magnet URI for a given torrent *already in Transmission*

Please note that `torrent-add` has no such support.
