### ISSUE TITLE
Rename : Invalid argument

### ISSUE THREAD

**Issue by vipera7** [brycied00d/PHP-Transmission-Class#30]
Hello,

I'm trying to use the function rename but when I use it I get an error.

```
<?php
$id_torrent = 1;
$rpc = new TransmissionRPC('http://example.com:9091/transmission/rpc', 'USERNAME', 'SECRET');
$result = $rpc->rename( $id_torrent, "/downloads/complete/", "Testfile.pdf" );
```

Result :

```
object(stdClass)#374 (2) {
  ["arguments"]=>
  object(stdClass)#412 (3) {
    ["id"]=>
    int(1)
    ["name"]=>
    string(12) "Testfile.pdf"
    ["path"]=>
    string(52) "/downloads/complete/"
  }
  ["result"]=>
  string(16) "Invalid argument"
}
```

**Comment by brycied00d** [comment]
The arguments to `rename` are ID, current path, new name (see https://github.com/brycied00d/PHP-Transmission-Class/blob/master/class/TransmissionRPC.class.php#L341-L345), so what your call `rename( $id_torrent, "/downloads/complete/", "Testfile.pdf" )` is telling Transmission to do is to rename a directory `/downloads/complete/` into a single file named `Testfile.pdf` which isn't possible.

Try `rename( $id_torrent, "Testfile.pdf", "/downloads/complete/")` to put `Testfile.pdf` into `/downloads/complete/`.

(Note: I haven't touched this code, or Transmission itself, in close to a decade so I may be misremembering things or it may be a different issue altogether.)
